# Generated by Django 4.2 on 2024-06-27 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(default='', max_length=50, verbose_name='住所'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default='', max_length=30, verbose_name='名前'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='furigana',
            field=models.CharField(default='', max_length=30, validators=[django.core.validators.RegexValidator('^[ァ-ヶー]+$', 'カタカナで入力してください。')], verbose_name='フリガナ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(message='正しい電話番号の形式で入力してください（例: 090-1234-5678）。', regex='^\\d{2,4}-\\d{2,4}-\\d{4}$')], verbose_name='電話番号'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='postal_code',
            field=models.CharField(default='', max_length=7, validators=[django.core.validators.RegexValidator(message='郵便番号は7桁の数字で入力してください。', regex='^\\d{7}$')], verbose_name='郵便番号*ハイフンなし'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True, verbose_name='メールアドレス'),
        ),
    ]
