# Generated by Django 4.2 on 2024-06-21 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gourmet', '0002_storeinfo_delete_examplemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', '和食'), ('2', '中華'), ('3', 'イタリアン'), ('4', 'フレンチ')], max_length=50, verbose_name='ジャンル')),
            ],
        ),
        migrations.AlterField(
            model_name='storeinfo',
            name='photo1',
            field=models.ImageField(blank=True, default='noImage.png', upload_to='', verbose_name='写真1'),
        ),
        migrations.AlterField(
            model_name='storeinfo',
            name='photo2',
            field=models.ImageField(blank=True, default='noImage.png', upload_to='', verbose_name='写真2'),
        ),
        migrations.AlterField(
            model_name='storeinfo',
            name='photo3',
            field=models.ImageField(blank=True, default='noImage.png', upload_to='', verbose_name='写真3'),
        ),
        migrations.AddField(
            model_name='storeinfo',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gourmet.category'),
            preserve_default=False,
        ),
    ]
