# Generated by Django 4.2 on 2024-06-21 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gourmet', '0005_remove_storeinfo_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('1', '和食'), ('2', '中華'), ('3', 'イタリアン'), ('4', 'フレンチ')], default=1, max_length=50, verbose_name='ジャンル'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storeinfo',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gourmet.category'),
            preserve_default=False,
        ),
    ]
