# Generated by Django 4.2 on 2024-06-21 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gourmet', '0006_remove_category_name_category_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('1', '和食'), ('2', '中華'), ('3', 'イタリアン'), ('4', 'フレンチ'), ('5', '寿司'), ('6', '焼肉')], max_length=50, verbose_name='ジャンル'),
        ),
        migrations.AlterField(
            model_name='storeinfo',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gourmet.category', verbose_name='ジャンル'),
        ),
    ]
